package main

import "testing"

// TestNegamaxGoldenRoots pins the minimax→negamax migration: at the root the
// side to move is always the engine, so the engine-perspective root score is
// unchanged by the perspective rewrite and the negamax engine must reproduce
// the pre-conversion two-role minimax values bit for bit. Baseline captured
// from the minimax implementation immediately before the conversion.
// LMR is disabled here: it is value-changing by design, so the golden gate
// pins the value-preserving stack (incremental candidates, TT, aspiration).
//
// Bonus-semantics pin (kept for the posEnabled=true A/B variant, off by
// default): the pyramid bonus shifts every non-tactical score by its small
// magnitude, 12/13 moves unchanged, ownThree d2 re-selects within a tie (83
// vs 79, both live-four makers). Captured values: oppThree -100530/-600/
// -19190, ownThree 100540@83, midgame11 4950/3060/50, blockedFour -620/
// -32340/-34480, midgame15 -8470.
func TestNegamaxGoldenRoots(t *testing.T) {
	diagrams := map[string]string{
		"oppThree": `
...........
...........
...........
...........
...........
...........
...........
....xxx....
...........
...........
...........
`,
		"ownThree": `
...........
...........
...........
...........
...........
...........
...........
...ooo.....
...........
...........
...........
`,
		"midgame11": `
...........
.....x.....
...........
...........
......o....
...........
....o.x....
...........
...........
...........
...........
`,
		"blockedFour": `
...........
...........
...........
...........
...........
...........
....oxxxx..
...........
...........
...........
...........
`,
	}
	cases := []struct {
		name        string
		depth       int
		score, move int
	}{
		{"oppThree", 2, -100450, 80},
		{"oppThree", 4, -500, 80},
		{"oppThree", 6, -19150, 80},
		{"ownThree", 2, 100450, 79},
		{"ownThree", 4, 9999998, 79},
		{"ownThree", 6, 9999998, 79},
		{"midgame11", 2, 4900, 60},
		{"midgame11", 4, 3000, 48},
		{"midgame11", 6, 0, 48},
		{"blockedFour", 2, -500, 75},
		{"blockedFour", 4, -32250, 75},
		{"blockedFour", 6, -34350, 75},
		{"midgame15", 8, -8500, 64},
	}
	for _, c := range cases {
		var s *searcher
		if c.name == "midgame15" {
			const n = 15
			stones := [][3]int{
				{7, 7, playerMe}, {8, 8, playerOpp}, {7, 8, playerMe}, {9, 9, playerOpp},
				{6, 6, playerMe}, {8, 7, playerOpp}, {9, 7, playerMe}, {10, 10, playerOpp},
			}
			b := make([]int, n*n)
			for _, st := range stones {
				b[st[1]*n+st[0]] = st[2]
			}
			s = newSearcher(n, b, 0)
		} else {
			s = diagramToSearcher(t, diagrams[c.name])
		}
		s.lmrEnabled = false    // golden gate: value-preserving stack only
		s.qThreeEnabled = false // three-extending quiescence is value-changing too
		score, mv, ok := s.searchRoot(c.depth, s.genMoves(rootMoveLimit, playerMe))
		if !ok {
			t.Fatalf("%s depth %d: root search aborted", c.name, c.depth)
		}
		if score != c.score || mv != c.move {
			t.Errorf("%s depth %d: negamax root = (score %d, move %d), minimax baseline = (%d, %d)",
				c.name, c.depth, score, mv, c.score, c.move)
		}
	}
}
