package main

import "testing"

// TestNegamaxGoldenRoots pins the value-preserving search stack (incremental
// candidates, TT, aspiration; LMR and the three-extending quiescence are
// value-changing and disabled here). Baselines re-captured after the
// candidate-ladder rung merge (both-role rungs, reference eval.js): the tree
// now includes the opponent's own counter-threats at opponent-to-move nodes
// and the engine's rush fours at live-four nodes, so exact values shifted —
// mostly less optimistic (hidden replies visible), occasionally better (own
// counter-fours searchable). The perspective-migration guarantee this test
// was written for (negamax == two-role minimax on the same generator) is
// re-checked by the equivalence suites in tt_test.go.
//
// Bonus-semantics pin (kept for the posEnabled=true A/B variant, off by
// default): the pyramid bonus shifts every non-tactical score by its small
// magnitude, 12/13 moves unchanged, ownThree d2 re-selects within a tie (83
// vs 79, both live-four makers).
func TestNegamaxGoldenRoots(t *testing.T) {
	diagrams := map[string]string{
		"oppThree": `
...........
...........
...........
...........
...........
...........
...........
....xxx....
...........
...........
...........
`,
		"ownThree": `
...........
...........
...........
...........
...........
...........
...........
...ooo.....
...........
...........
...........
`,
		"midgame11": `
...........
.....x.....
...........
...........
......o....
...........
....o.x....
...........
...........
...........
...........
`,
		"blockedFour": `
...........
...........
...........
...........
...........
...........
....oxxxx..
...........
...........
...........
...........
`,
	}
	cases := []struct {
		name        string
		depth       int
		score, move int
	}{
		{"oppThree", 2, -100450, 80},
		{"oppThree", 4, -500, 80},
		{"oppThree", 6, -32250, 80},
		{"ownThree", 2, 100450, 79},
		{"ownThree", 4, 9999998, 79},
		{"ownThree", 6, 9999998, 79},
		{"midgame11", 2, 4900, 60},
		{"midgame11", 4, 0, 48},
		{"midgame11", 6, 2900, 48},
		{"blockedFour", 2, -500, 75},
		{"blockedFour", 4, -32250, 75},
		{"blockedFour", 6, -100700, 75},
		{"midgame15", 8, -18350, 158},
	}
	for _, c := range cases {
		var s *searcher
		if c.name == "midgame15" {
			const n = 15
			stones := [][3]int{
				{7, 7, playerMe}, {8, 8, playerOpp}, {7, 8, playerMe}, {9, 9, playerOpp},
				{6, 6, playerMe}, {8, 7, playerOpp}, {9, 7, playerMe}, {10, 10, playerOpp},
			}
			b := make([]int, n*n)
			for _, st := range stones {
				b[st[1]*n+st[0]] = st[2]
			}
			s = newSearcher(n, b, 0)
		} else {
			s = diagramToSearcher(t, diagrams[c.name])
		}
		s.lmrEnabled = false    // golden gate: value-preserving stack only
		s.qThreeEnabled = false // three-extending quiescence is value-changing too
		score, mv, ok := s.searchRoot(c.depth, s.genMoves(rootMoveLimit, playerMe))
		if !ok {
			t.Fatalf("%s depth %d: root search aborted", c.name, c.depth)
		}
		if score != c.score || mv != c.move {
			t.Errorf("%s depth %d: negamax root = (score %d, move %d), minimax baseline = (%d, %d)",
				c.name, c.depth, score, mv, c.score, c.move)
		}
	}
}
