package alphabeta

import "testing"

// Search benchmarks on fixed diagrams, searched with searchRoot at a fixed
// depth. Every iteration builds a fresh searcher (cold TT, zero deadline), so
// the numbers are fully deterministic and comparable across engine versions.
// Run with:
//
//	go test -run '^$' -bench BenchmarkSearch -benchtime 1x -v
//
// Ordering and pruning improvements should show up as fewer nodes and fewer
// microseconds per node, not just faster wall time.

// midgameDiagram: both sides are developing, the strongest shapes are live
// twos and sleep threes, so the search is wide and move ordering (killers,
// history, TT move) does the pruning work.
const midgameDiagram = `
...............
...............
...............
...............
......x........
.....o.x.......
.....o..x......
........o......
....x...o......
...............
...............
...............
...............
...............
...............
`

// tacticalDiagram: both sides threaten — the engine has a jump three and the
// opponent a live three — so the search runs through forcing sequences where
// alpha-beta cuts hardest.
const tacticalDiagram = `
...............
...............
...............
...............
...............
...............
...............
.......oo.o....
........xxx....
......x........
...............
...............
...............
...............
...............
`

func BenchmarkSearchMidgame(b *testing.B) { benchSearch(b, midgameDiagram, 12) }

func BenchmarkSearchTactical(b *testing.B) { benchSearch(b, tacticalDiagram, 12) }

func benchSearch(b *testing.B, diagram string, depth int) {
	var nodes, cuts int
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		s := diagramToSearcher(b, diagram)
		moves := s.genMoves(rootMoveLimit, playerMe)
		s.searchRoot(depth, moves)
		nodes, cuts = s.nodes, s.abCuts
	}
	b.StopTimer()
	b.Logf("nodes=%d abCuts=%d", nodes, cuts)
}
