package alphabeta

import (
	"testing"
	"time"
)

// TestKillSearchFindsVCF: with a double open three (a proven forced win via
// live fours), the kill search must report it. The shape gives o two crossing
// open threes; any defence still leaves a live-four → five.
func TestKillSearchFindsVCF(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
.........
.........
...o.o...
...o.o...
....x....
`)
	r := s.runKillSearch(2 * time.Second)
	if r < 0 {
		t.Fatal("kill search missed a double-three forced win")
	}
	x, y := r%9, r/9
	// every winning start is on one of the two threes
	if !((y == 6 || y == 7) && (x == 2 || x == 3 || x == 5 || x == 7)) {
		t.Fatalf("kill move = (%d,%d), want a point on the threes", x, y)
	}
}

// TestKillSearchSimpleFourWin: with a live four on the board the kill search
// (and the tactical shortcut) must complete the five.
func TestKillSearchSimpleFourWin(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
.........
.........
...oooo..
..xx.....
.........
`)
	r := s.runKillSearch(2 * time.Second)
	if r < 0 {
		t.Fatal("kill search missed a trivial four completion")
	}
	x, y := r%9, r/9
	if y != 6 || (x != 2 && x != 7) {
		t.Fatalf("kill move = (%d,%d), want (2,6)/(7,6)", x, y)
	}
}

// TestKillSearchVCFChain: attacker can build four-after-forced-block.
// Shape (9x9, o to move):
//
//	row4: . . . o o . .   → play (2,4) makes .ooo o? no—
//
// We use a textbook double-threat: o at (3,4),(4,4) plus (4,3),(3,5)diag…
// simplest verifiable chain: open three; opponent has no fours, so VCT finds
// live-four → win in 3 attacker moves.
func TestKillSearchVCTOpenThree(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
.........
.........
.........
...ooo...
.........
`)
	r := s.runKillSearch(3 * time.Second)
	if r < 0 {
		t.Fatal("kill search missed a forced win from an open three")
	}
	x, y := r%9, r/9
	// the winning start is one of the live-four-making extensions or the gap
	if y != 7 || (x != 1 && x != 2 && x != 6 && x != 7) {
		t.Fatalf("kill move = (%d,%d), want an extension of the three on row 7", x, y)
	}
}

// TestKillSearchNoFalsePositive: a quiet position with no forcing win must
// NOT report a kill.
func TestKillSearchNoFalsePositive(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
....o....
...x.x...
.........
.........
.........
`)
	if r := s.runKillSearch(time.Second); r >= 0 {
		t.Fatalf("kill search reported a fake kill at (%d,%d)", r%9, r/9)
	}
}

// TestKillSearchDefendedByCounterFour: attacker's open three is answered by a
// defender who owns a rush four — the kill must be refuted.
func TestKillSearchDefendedByCounterFour(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
...ooo...
.........
..xxxx...
.........
.........
`)
	if r := s.runKillSearch(time.Second); r >= 0 {
		t.Fatalf("kill reported despite defender's four: (%d,%d)", r%9, r/9)
	}
}

// TestKillSearchRushFourNotAKill: a three with ONE end blocked can only be
// extended into a rush four, which the defender blocks — no forced win.
// Regression: the kill search used to treat "defender has no counter-four"
// as "defender has no defence" and declared this a win at (6,4).
func TestKillSearchRushFourNotAKill(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
..xooo...
.........
.........
.........
.........
`)
	if r := s.runKillSearch(2 * time.Second); r >= 0 {
		t.Fatalf("blockable rush four reported as a kill at (%d,%d)", r%9, r/9)
	}
}

// TestKillSearchVCFThroughForcedBlock: a sound kill that goes THROUGH the
// defender's forced block must still be found: rush four (block forced) →
// live four from the second three (block forced) → five.
func TestKillSearchVCFThroughForcedBlock(t *testing.T) {
	// row 4: x o o o .  → (6,4) rush four, block (7,4) forced
	// col 5: o (5,4) o (5,5) o (5,6) — live three, live-four makers (5,3)/(5,7)
	s := diagramToSearcher(t, `
.........
.........
.........
.........
..xooo...
......o..
......o..
.........
.........
`)
	r := s.runKillSearch(2 * time.Second)
	if r < 0 {
		t.Fatal("kill search lost the forced-block VCF chain")
	}
	x, y := r%9, r/9
	// (6,4) is the plain rush four, (7,4) the jump four (ooo.o) — both force
	// the block at (6,4) and then win through the column-5 live three
	if y != 4 || (x != 6 && x != 7) {
		t.Fatalf("kill move = (%d,%d), want a four-maker on row 4 ((6,4)/(7,4))", x, y)
	}
}

// TestKillSearchLiveTwoNotAKill: a lone live two is the most common middlegame
// shape — growing it into a three is answered by blocking, so it must NOT be
// proven a kill. Regression: the defender's move set had no "block the
// attacker's live three" option, so the moment the attacker grew a two into a
// fresh three, the defender had nothing to play and the attack continued
// unchecked — every live two was a phantom forced win.
func TestKillSearchLiveTwoNotAKill(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
....oo...
.........
.........
.........
.........
`)
	if r := s.runKillSearch(2 * time.Second); r >= 0 {
		t.Fatalf("blockable live two reported as a kill at (%d,%d)", r%9, r/9)
	}
}

// TestKillSearchFreshThreeDefended: a lone live two flanked by defender
// stones must survive the multi-ply defence chain: the attacker grows a
// three, the defender blocks it; the attacker converts to a rush four, the
// defender blocks the five point; the attacker runs out of forcing moves.
func TestKillSearchFreshThreeDefended(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
..x...x..
.........
...oo....
.........
.........
.........
`)
	if r := s.runKillSearch(2 * time.Second); r >= 0 {
		t.Fatalf("blockable fresh threes reported as a kill at (%d,%d)", r%9, r/9)
	}
}

// TestKillSearchVCTPerfSanity: the block-three addition widens the defender's
// branch — VCT must still finish a threat-dense position comfortably inside
// its quarter-budget slice. The diagram has fours and threes for both sides
// but no forced win (defender holds counter-fours).
func TestKillSearchVCTPerfSanity(t *testing.T) {
	if testing.Short() {
		t.Skip("timing-sensitive")
	}
	s := diagramToSearcher(t, `
.........
.........
..x.oo...
...xoo...
..x.oo...
...x.....
.........
.........
.........
`)
	start := time.Now()
	r := s.runKillSearch(2 * time.Second)
	elapsed := time.Since(start)
	t.Logf("kill search on mixed-threat board: move=%d, elapsed=%v", r, elapsed)
	// generous ceiling: a quarter-budget probe on a dense 9x9 board must
	// resolve in well under a second, not approach its deadline
	if elapsed > 800*time.Millisecond {
		t.Fatalf("VCT too slow after widening the defence set: %v", elapsed)
	}
}

// TestOppKillProbeBlocksOpponentKill: the defence probe answers a live three
// that would otherwise cost the engine the race — the probe proves the
// opponent's kill (three → live four → unstoppable), the engine occupies a
// growth point, and the re-probe verifies the three is dead.
func TestOppKillProbeBlocksOpponentKill(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
.........
..xxx....
.........
...o.....
.........
`)
	r := s.runOppKillProbe(2 * time.Second)
	if r < 0 {
		t.Fatal("defence probe missed the opponent's live-three kill")
	}
	x, y := r%9, r/9
	if y != 5 || (x != 1 && x != 5) {
		t.Fatalf("probe move = (%d,%d), want a growth point of the three", x, y)
	}
}

// TestOppKillProbeLiveTwoNotAKill: a lone opponent live two is blockable —
// the probe must not report a kill (role-swapped twin of
// TestKillSearchLiveTwoNotAKill).
func TestOppKillProbeLiveTwoNotAKill(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
....xx...
.........
.........
.........
.........
`)
	if r := s.runOppKillProbe(2 * time.Second); r >= 0 {
		t.Fatalf("blockable opponent live two reported as a kill at (%d,%d)", r%9, r/9)
	}
}

// TestOppKillProbeRejectsUnblockableFork: two crossing opponent threes are a
// real fork — occupying one growth point leaves the other three alive, so the
// verification step must reject the block and the probe returns -1 (the main
// search's move stands; the position is simply lost).
func TestOppKillProbeRejectsUnblockableFork(t *testing.T) {
	s := diagramToSearcher(t, `
.........
.........
.........
.........
.........
..xxx....
.........
.....xxx.
.........
`)
	if r := s.runOppKillProbe(2 * time.Second); r >= 0 {
		t.Fatalf("unblockable double three reported as a single-point defence at (%d,%d)", r%9, r/9)
	}
}
